num = @{ int ~ ("." ~ ASCII_DIGIT*)? ~ (^"e" ~ int)? }
    int = { ("+" | "-")? ~ ASCII_DIGIT+ }

arg = { "x" }

operation = _{ add | subtract | multiply | divide }
    add      = { "+" }
    subtract = { "-" }
    multiply = { "*" }
    divide   = { "/" }

const_operation = _{ power_c }   
    power_c  = { "^" }

expr = { term ~ (operation ~ term | const_operation ~ num)* }
term = _{ arg | num | "(" ~ expr ~ ")" }

function = _{ SOI ~ expr ~ EOI }

WHITESPACE = _{ " " | "\t" }
